export const mockData = {
  data: {
    product: {
      id: 5485552,
      title:
        "JM Bullion Starter Pack – 1 oz JM Bullion Eagle Silver Tube (10 Rounds, Reverse Proof-Like, New)",
      thumbnail:
        "https://www.jmbullion.com/wp-content/uploads/2023/08/Starter-Pack-08292023-250x250.png",
      sku: "SRSMIJMBTUBE10",
      metal: "XAG",
      weight: "10.00000",
      description:
        "<h2>The JM Bullion Starter Pack</h2>\n<p><strong>(Limit of 10 Oz at Spot Per Customer/Household)</strong></p>\n<p>Start your precious metals portfolio with a 10 oz tube of silver rounds, offered at spot price!</p>\n<ul>\n<li>New silver rounds from a trusted American mint</li>\n<li>Each tube contains ten 1 oz .999 silver rounds</li>\n<li>Ships in plastic tube, inside of a custom velvet pouch</li>\n<li>All orders include tracking and insurance</li>\n<li>Ships within 1 business day of cleared payment</li>\n<li>10 oz at spot offer limited to one per household.</li>\n</ul>\n",
      slug: "jm-bullion-starter-pack-1-oz-jm-bullion-eagle-silver-tube-10-rounds-reverse-proof-like-new",
      permalink: "https://sandbox-ca.jmbullion.com/starter-pack/",
      stockStatus: "instock",
      quantity: 562,
      ribbon: "",
      hidePrice: 0,
      fixedPrice: false,
      premiumOptic: "",
      images: [
        "https://www.jmbullion.com/wp-content/uploads/2023/07/starterpack-buffalo-noyear_360.jpg",
      ],
      engraving: false,
      pricingTiers: [
        {
          quantityRange: "1",
          echeck: 309.4,
          card: 322.29,
          crypto: 312.62,
        },
      ],
      reviews: {
        totalRatings: 0,
        totalReviews: 127,
        averageRating: null,
        reviewData: [
          {
            id: 1,
            reviewStar: 5,
            revierName: 'Raymond',
            reviwerDate: 'January 15, 2025',
            review: 'Excellent product and excellent value… JMB is one of my go to online sources… Never a problem or worry',
          },
          {
            id: 2,
            reviewStar: 2,
            revierName: 'Jay',
            reviwerDate: 'January 02, 2025',
            review: 'The product was really good but I knew sooner or later the shipping would not deliver in person but would leave in the mailbox. And it happened. I was waiting for nothing.',
          },
          {
            id: 3,
            reviewStar: 1,
            revierName: '',
            reviwerDate: 'December 30, 2024',
            review: 'Slow to process and Sent on the slow boat. 16 days from order to delivery.',
          },
          {
            id: 101,
            reviewStar: 5,
            revierName: 'Raymond',
            reviwerDate: 'January 15, 2025',
            review: 'Excellent product and excellent value… JMB is one of my go to online sources… Never a problem or worry',
          },
          {
            id: 102,
            reviewStar: 2,
            revierName: 'Jay',
            reviwerDate: 'January 02, 2025',
            review: 'The product was really good but I knew sooner or later the shipping would not deliver in person but would leave in the mailbox. And it happened. I was waiting for nothing.',
          },
          {
            id: 103,
            reviewStar: 1,
            revierName: '',
            reviwerDate: 'December 30, 2024',
            review: 'Slow to process and Sent on the slow boat. 16 days from order to delivery.',
          },
          {
            id: 104,
            reviewStar: 5,
            revierName: 'Raymond',
            reviwerDate: 'January 15, 2025',
            review: 'Excellent product and excellent value… JMB is one of my go to online sources… Never a problem or worry',
          },
          {
            id: 105,
            reviewStar: 2,
            revierName: 'Jay',
            reviwerDate: 'January 02, 2025',
            review: 'The product was really good but I knew sooner or later the shipping would not deliver in person but would leave in the mailbox. And it happened. I was waiting for nothing.',
          },
          {
            id: 106,
            reviewStar: 1,
            revierName: '',
            reviwerDate: 'December 30, 2024',
            review: 'Slow to process and Sent on the slow boat. 16 days from order to delivery.',
          },
          {
            id: 107,
            reviewStar: 5,
            revierName: 'Raymond',
            reviwerDate: 'January 15, 2025',
            review: 'Excellent product and excellent value… JMB is one of my go to online sources… Never a problem or worry',
          },
          {
            id: 108,
            reviewStar: 2,
            revierName: 'Jay',
            reviwerDate: 'January 02, 2025',
            review: 'The product was really good but I knew sooner or later the shipping would not deliver in person but would leave in the mailbox. And it happened. I was waiting for nothing.',
          },
          {
            id: 6,
            reviewStar: 1,
            revierName: '',
            reviwerDate: 'December 30, 2024',
            review: 'Slow to process and Sent on the slow boat. 16 days from order to delivery.',
          },
          {
            id: 7,
            reviewStar: 5,
            revierName: 'Raymond',
            reviwerDate: 'January 15, 2025',
            review: 'Excellent product and excellent value… JMB is one of my go to online sources… Never a problem or worry',
          },
          {
            id: 8,
            reviewStar: 2,
            revierName: 'Jay',
            reviwerDate: 'January 02, 2025',
            review: 'The product was really good but I knew sooner or later the shipping would not deliver in person but would leave in the mailbox. And it happened. I was waiting for nothing.',
          },
          {
            id: 9,
            reviewStar: 1,
            revierName: '',
            reviwerDate: 'December 30, 2024',
            review: 'Slow to process and Sent on the slow boat. 16 days from order to delivery.',
          },
          {
            id: 10,
            reviewStar: 5,
            revierName: 'Raymond',
            reviwerDate: 'January 15, 2025',
            review: 'Excellent product and excellent value… JMB is one of my go to online sources… Never a problem or worry',
          },
          {
            id: 11,
            reviewStar: 2,
            revierName: 'Jay',
            reviwerDate: 'January 02, 2025',
            review: 'The product was really good but I knew sooner or later the shipping would not deliver in person but would leave in the mailbox. And it happened. I was waiting for nothing.',
          },
          {
            id: 12,
            reviewStar: 1,
            revierName: '',
            reviwerDate: 'December 30, 2024',
            review: 'Slow to process and Sent on the slow boat. 16 days from order to delivery.',
          },
        ],
      },
    },
  },
};
